//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PF_Wave_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLES_FACTURA = new HashSet<DETALLES_FACTURA>();
            this.PRODUCTOS_SUCURSAL = new HashSet<PRODUCTOS_SUCURSAL>();
        }
    
        public int Id_producto { get; set; }
        public string Nombre_producto { get; set; }
        public int Id_proveedor_producto { get; set; }
        public string EAN { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_FACTURA> DETALLES_FACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOS_SUCURSAL> PRODUCTOS_SUCURSAL { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
