//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PF_Wave_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bajoInventario
    {
        public string Nombre_sucursal { get; set; }
        public string Nombre_producto { get; set; }
        public int Cantidad_bodega { get; set; }
        public int Cantidad_promedio { get; set; }
    }
}
