//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PF_Wave_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJEROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAJEROS()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public int Id_sesion_caja { get; set; }
        public int Id_caja_cajeros { get; set; }
        public int Id_cajero { get; set; }
        public System.DateTime Fecha_apertura { get; set; }
        public int Cantidad_apertura { get; set; }
        public Nullable<System.DateTime> Fecha_clausura { get; set; }
        public Nullable<int> Cantidad_clausura { get; set; }
    
        public virtual CAJA CAJA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
