//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PF_Wave_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLES_FACTURA
    {
        public int Id_factura_DF { get; set; }
        public int Id_detalle_DF { get; set; }
        public int Id_producto_DF { get; set; }
        public int Cantidad_compra { get; set; }
        public decimal Precio_factura { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
