//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PF_Wave_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.DETALLES_FACTURA = new HashSet<DETALLES_FACTURA>();
        }
    
        public int Id_factura { get; set; }
        public int Id_sesion_caja_factura { get; set; }
        public int Cedula_cliente { get; set; }
        public System.DateTime Fecha_factura { get; set; }
        public System.TimeSpan Hora_apertura { get; set; }
        public Nullable<System.TimeSpan> Hora_clausura { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CAJEROS CAJEROS { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_FACTURA> DETALLES_FACTURA { get; set; }
    }
}
