//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PF_Wave_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class minutosPromedioCajero
    {
        public string Nombre_persona { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public System.DateTime Fecha_factura { get; set; }
        public int Cantidad_compra { get; set; }
        public Nullable<int> minutos_en_atencion { get; set; }
    }
}
