//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PF_Wave_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS_SUCURSAL
    {
        public int Id_sucursal_PS { get; set; }
        public int Id_producto_PS { get; set; }
        public int Cantidad_bodega { get; set; }
        public int Cantidad_promedio { get; set; }
        public decimal Precio_sucursal { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
